### ISSUE TITLE
Text hidden in HDR. For mica

### ISSUE THREAD

**Issue by Battler624** [ozone10/Npp-DarkNpp#2]
Enabling dark mode in note++ and enabling this plugin on anything other than none makes the text completely hidden.

Unfortunately idk how to record this without a phone (OBS captures it fine without any text issues)

**Comment by Battler624** [comment]
https://github.com/ozone10/Npp-DarkNpp/assets/9511158/65ea09b8-74fc-464e-9223-f7385248edff

**Comment by Battler624** [comment]
Issue could be bigger, same thing happens with micaforeveryone

**Comment by ozone10** [comment]
I will look into it, but no promise.

**Comment by ozone10** [comment]
Unfortunately after some research, this is Windows bug. Mica won't work properly with HDR or ACM (auto color management) enabled for win32 apps.
