### ISSUE TITLE
[Bug] Window contents dissapear on a second monitor

### ISSUE THREAD

**Issue by emvaized** [ozone10/Npp-DarkNpp#4]
I have a weird bug: with "DarkNpp" plugin enabled, whenever I drag Notepad++ window to my second display (secondary display on the left) all window contents dissapear. Basically anything which contains text dissapear (text editor itself, main menu, tab bar labels). But when I enter "Print Screen" to capture a screenshot, contents are shown with no problem. 

Here's a small screen recording illustrating my problem: 
![5336932675611549648-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/e6df08a1-95d5-4ce7-a907-110263d08fc2)

It might be important to note that I use different resolutions and scaling on monitors, and Windows 11 23H2. Problem dissapears when I disable DarkNpp plugin.

**Comment by ozone10** [comment]
@emvaized 
known issue (#2).
Unfortunately this is Windows bug.

**Comment by emvaized** [comment]
@ozone10 
Thanks a lot for your response! 
I disabled Auto Color Management on a second monitor now, and the problem is gone.
